# Generated by Django 2.2.7 on 2019-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191125_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\USER\\Desktop\\django text\\media'),
        ),
    ]
