# Generated by Django 2.2.7 on 2019-11-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20191125_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadss',
            name='name',
        ),
    ]
