# Generated by Django 2.2.7 on 2019-11-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20191125_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadss',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
