# Generated by Django 2.2.7 on 2019-11-26 10:22

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_uploadss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.FileField(upload_to=gallery.models.user_directory_path),
        ),
    ]
