# Generated by Django 2.2.7 on 2019-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20191126_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\USER\\Desktop\\django text\\media'),
        ),
    ]
