# Generated by Django 2.2.7 on 2019-12-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20191201_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='filename',
            new_name='filenamee',
        ),
    ]
