# Generated by Django 2.2.7 on 2019-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20191201_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadsss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filenamee', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
