# Generated by Django 2.2.7 on 2019-12-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_delete_uploadss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadsss',
            new_name='uploadss',
        ),
    ]
