# Generated by Django 2.2.7 on 2019-12-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20191202_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadss',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
