# Generated by Django 2.2.7 on 2019-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20191202_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadsss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='C:\\Users\\USER\\Desktop\\django text\\media')),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
