# Generated by Django 2.2.7 on 2019-12-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_uploadsss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploads',
        ),
    ]
