# Generated by Django 2.2.7 on 2019-12-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_delete_uploads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadsss',
            new_name='uploads',
        ),
    ]
