# Generated by Django 2.2.7 on 2019-12-17 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_auto_20191217_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
