# Generated by Django 2.2.7 on 2019-12-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20191217_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
