# Generated by Django 2.2.7 on 2019-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0025_auto_20191217_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
