# Generated by Django 2.2.7 on 2019-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_auto_20191217_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
