# Generated by Django 2.2.7 on 2019-12-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('gallery', '0030_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
