# Generated by Django 2.2.7 on 2019-12-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='username',
            new_name='author',
        ),
    ]
