# Generated by Django 2.2.7 on 2019-12-27 23:45

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_auto_20191228_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.FileField(upload_to=gallery.models.user_directory_path),
        ),
    ]
