# Generated by Django 2.2.7 on 2019-12-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_auto_20191228_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='username',
            field=models.CharField(default='joshijax', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploads',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
