# Generated by Django 2.2.7 on 2020-01-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0034_auto_20191228_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='renamefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
