# Generated by Django 2.2.7 on 2020-01-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0035_renamefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
