# Generated by Django 2.2.7 on 2020-01-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0036_uploads_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='state',
        ),
    ]
