# Generated by Django 2.2.7 on 2020-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0037_remove_uploads_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='file_name1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploads',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
